### ISSUE TITLE
Templatitator example in the documentation is not working out of the box

### ISSUE THREAD

**Issue by RutgerRauws** [Gottwik/enduro_website#10]
Hi, I'm new to Enduro.js and was following [the documentation to split templates into multiple files](http://www.endurojs.com/docs/templatitator#splitting-templates-into-multiple-files).

The example did not work for me and was throwing errors on unexpected braces in `dog.js` and `parrot.js`. It took me a while to find out that the given code, i.e.
```js
animal_types: {
    dog: {
        $animal_type_type: 'title',
        animal_type: 'dog',
        name: '',
        barks: false
    },
},
```
had to be encapsulated by braces:
```js
{
    animal_types: {
        dog: {
            $animal_type_type: 'title',
            animal_type: 'dog',
            name: '',
            barks: false
        },
    },
}
```
in order to make it work. This only became clear to me when reading the [globalizer documentation](http://www.endurojs.com/docs/globalizer), which I didn't do yet as I was not going through the documentation in sequence and only looking at the parts that seemed interesting to my use case.

After the troubleshooting, it makes sense to read the globalizer chapter first. This chapter is indeed also listed before the templatitator chapter, but I expect more people than only me focus on specific chapters and skip over some info. Therefore I would propose to change the examples so they are 'copy-pastable'.

Other than that, keep up the great work! It's a very easy framework to work with.

**Comment by Gottwik** [comment]
hey, sorry you had this experience. I went ahead and made enduro respect these files as well. In the end the outer-most braces are useless.

Let us know if you run into other issues 😄

**Comment by RutgerRauws** [comment]
No problem, the rest of the experience was a total bliss! Thanks for your fast response and implementation :+1:
