### ISSUE TITLE
Custom themes

### ISSUE THREAD

**Issue by karneaud** [Gottwik/enduro_website#5]
If I wanted to create custom themes that can be install via the command line what do I need to do?

**Comment by Gottwik** [comment]
Hey @karneaud, I am psyched you would like to create a theme.

I am happy to add the theme if you provide a github repository for the theme, or you can just update and pull-request this file: https://github.com/Gottwik/enduro_website/blob/master/cms/global/theme_manager/themes.js

Let me know if you need any help with this.

**Comment by karneaud** [comment]
@Gottwik Just a suggestion. Is there a way that we can add themes via github or a more public/ general/ generic package manager search? Or even implement a search via local directory?

**Comment by Gottwik** [comment]
Well, that is an awesome idea. I will try to get an visual interface for uploading themes going to empower people to create themes.

**Comment by karneaud** [comment]
Why visual interface? That be long term. if there is a way to input a git url instead of a theme name....that could be a lot easier for the time being. I see you have a `get_theme_from_gz_link` or something of the sort.

**Comment by karneaud** [comment]
@Gottwik in this website repo you make use of this 
https://github.com/Gottwik/enduro_website/blob/master/app/theme_manager/theme_manager.js which is different from the one in the *libs* directory. Can theme developers do same? Instead of mongo DB though we use Github/ NPM/ Yard repo searches?

**Comment by Gottwik** [comment]
I thought visual interface might be useful because there is more data to a theme, like a screenshot and labels...

The `theme_manager` in the enduro_website is to get all the themes and display them.

In the end, each theme has a git repository, so you can use npm or yarn to add it as dependency.

My main goal with the theme manager was to create an ease-of-access to new users. They can get a somewhat finished project running with enduro in 30 seconds.

Hey, just checking. You understand you can use enduro to create your own custom website without actually doing anything with the themes, right?

**Comment by karneaud** [comment]
> Hey, just checking. You understand you can use enduro to create your own custom website without actually doing anything with the themes, right?

Yeah...I'm a designer and developer. I need to outfit a website but want to make it theme interchangeable with the CMS. 

Can you have one website with 2 pages with two different themes?

**Comment by Gottwik** [comment]
Hey, I believe there is some confusion about what a theme is.

A theme is basically an enduro project that people can download easily by using the `enduro theme` cli command.

If you want to just create a page, you don't really need to touch themes. Just run `enduro create mynicepage` and start adding pages by editing .hbs files and so on. If you are very proud about the page you made you can make it available to other people by registering it as a theme. Currently, there is just the `mirror` theme.

Hey, I am here to help. Super-happy to try to answer any questions you might have.

**Comment by karneaud** [comment]
@Gottwik 

I think my question was not explained properly. it is two folded. 

I need to develop 2 "one page websites". Both with very different templates/ themes, styles and content. 

Yes I can just develop 2 enduro projects but I was wondering if enduro can do a multi sites with just one installation( kind of like wordpress MU where you have two separate sites managed by one CMS installation) 

The second part of my quest. Would be to take one of those themes and add it to you collection as an automated installable package so i can be installed via the `enduro theme thisnewtheme` command

I'm super excited about it myself and would keep you updated on my progress

**Comment by Gottwik** [comment]
Yea, it's a very good question:

**Can I have two websites running as 1 enduro project?**
Sure, just create two pages in /pages folder, apply different stylesheets, include different js files... You can share some of the context/cms data or have shared bower dependencies. This is a valid approach to create two small projects and save on hosting.

I believe wordpress was built with shared hosting in mind. On shared hosting, having one wordpress and many websites made much sense. Now, I suggest to just create two separate projects and host them separately in a container or Paas(Heroku).

You are extremely welcome to share those as themes. Don't hesitate to request support.
